### ISSUE TITLE
test suite failure with justified-containers-0.2.0.0

### ISSUE THREAD

**Issue by DanBurton** [matt-noonan/justified-containers#4] opened 2017-10-17 21:42 UTC
As seen on the stackage build server:

```
Failures:

  test/Data/Map/JustifiedSpec.hs:118: 
  1) Data.Map.Justified, at runtime, does not allocate key copies when gathering
 key evidence

  test/Data/Map/JustifiedSpec.hs:138: 
  2) Data.Map.Justified, at runtime, does not allocate values when performing lo
okup with a verified key

Randomized with seed 135551182
```

**Comment by matt-noonan** [comment] 2017-10-17 22:25
Thanks for the report, @DanBurton. I am unable to reproduce locally, can you provide some additional information?

That test does some hacky things to check if two values actually occupy the same location in memory, so it may be sensitive to the exact testing environment. Do you have details about the GHC version and system architecture?

**Comment by matt-noonan** [comment] 2017-10-18 02:03
I have now been able to reproduce the issue with GHC 8.2.1.

**Comment by mrkgnao** [comment] 2017-10-21 06:29
I also have a repro on NixOS with GHC 8.2.1. ([This](https://github.com/NixOS/nixpkgs/commit/48553c3a241df56d934b19d62ded50f03b8b606e) nixpkgs commit.)

**Comment by matt-noonan** [comment] 2017-10-28 14:49
It looks like the change in behavior began with [this GHC commit](https://github.com/ghc/ghc/commit/f0d98fc6cdde26bf43a04d9f01b6ad2f4c88f0b9#diff-95e107ab36c9beadfc459f7118eb03f8), that allowed GHC to be a little more clever about re-using shared values. See [this repo](https://github.com/matt-noonan/ptr-eq-test) for some dumps that show the behavior change.

In any case, it looks like marking `isLiterally` as `NOINLINE` gets the test cases back on the rails, at least for now. Alternately, running the tests with `-O0` should also work.

Fixed in https://github.com/matt-noonan/justified-containers/commit/7479da543ce129ce33ada8b438f7c6aa543cc5fb.

**Closed by matt-noonan** 2017-10-28 14:49 UTC
